# Generated by Django 5.0.4 on 2024-04-23 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Заказчик",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="executor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="executor",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Исполнитель",
            ),
        ),
        migrations.AddField(
            model_name="ordersresponses",
            name="orders",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders_responses",
                to="orders.order",
                verbose_name="Заказы",
            ),
        ),
        migrations.AddField(
            model_name="ordersresponses",
            name="responses",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders_responses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Отклики",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="responses",
            field=models.ManyToManyField(
                related_name="responses",
                through="orders.OrdersResponses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Отклики",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.UniqueConstraint(
                fields=("title", "customer"), name="uniq_title_customer"
            ),
        ),
    ]
