# Generated by Django 5.0.4 on 2024-04-21 22:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_alter_order_executor"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="name",
            new_name="title",
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.UniqueConstraint(
                fields=("title", "customer"), name="uniq_title_customer"
            ),
        ),
    ]
