# Generated by Django 5.0.4 on 2024-04-22 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_customuser_name_alter_customuser_first_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("Customer", "Заказчик"), ("Executor", "Исполнитель")],
                default="Заказчик",
            ),
        ),
    ]
