# Generated by Django 5.0.4 on 2024-04-22 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_customuser_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[("Customer", "Заказчик"), ("Executor", "Исполнитель")]
            ),
        ),
    ]
